# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.12-alpine3.23"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.12-alpine3.23"
  armhf: "ghcr.io/home-assistant/armhf-base-python:3.12-alpine3.23"
  armv7: "ghcr.io/home-assistant/armv7-base-python:3.12-alpine3.23"
  i386: "ghcr.io/home-assistant/i386-base-python:3.12-alpine3.23"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: SwitchBot MQTT Proxy"
  org.opencontainers.image.description: "SwitchBot MQTT Proxy"
  org.opencontainers.image.source: "https://github.com/DarwinInnovation/di-ha-addons"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
